{
 "title": "FireFly Performance",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(ff_apiserver_rest_requests_total, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(ff_apiserver_rest_requests_total, pod)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(ff_apiserver_rest_requests_total{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ff_apiserver_rest_request_duration_seconds_bucket{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Broadcast", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Submitted",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_broadcast_submitted_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_broadcast_confirmed_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_broadcast_rejected_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Time to Confirm",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(ff_broadcast_histogram_bucket{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "2xx Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=~\"/api/v1/namespaces/{ns}/messages/broadcast\",code=~\"200|202\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=\"/api/v1/namespaces/{ns}/messages/broadcast\",code=\"500\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ff_broadcast_submitted_total{namespace=\"$namespace\",pod=\"$pod\"}-ff_broadcast_confirmed_total{namespace=\"$namespace\",pod=\"$pod\"}+ff_broadcast_rejected_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "5xx Requests (/messages/broadcast)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=\"/api/v1/namespaces/{ns}/messages/broadcast\",code=\"500\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Private Message", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Submitted",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_private_msg_submitted_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_private_msg_confirmed_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_private_msg_rejected_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Time to Confirm",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(ff_private_msg_histogram_bucket{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "2xx Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=~\"/api/v1/namespaces/{ns}/messages/private\",code=~\"202\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=\"/api/v1/namespaces/{ns}/messages/private\",code=\"500\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ff_private_msg_submitted_total{namespace=\"$namespace\",pod=\"$pod\"}-ff_private_msg_confirmed_total{namespace=\"$namespace\",pod=\"$pod\"}+ff_private_msg_rejected_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "5xx Requests (/messages/private)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=\"/api/v1/namespaces/{ns}/messages/private\",code=\"500\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Mint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Submitted",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_mint_submitted_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_mint_confirmed_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_mint_rejected_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Time to Confirm",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(ff_mint_histogram_bucket{namespace=\"$namespace\",pod=\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "2xx Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=~\"/api/v1/namespaces/{ns}/tokens/mint\",code=~\"200|202\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=~\"/api/v1/namespaces/{ns}/tokens/mint\",code=\"500\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ff_mint_submitted_total{namespace=\"$namespace\",pod=\"$pod\"}-ff_mint_confirmed_total{namespace=\"$namespace\",pod=\"$pod\"}+ff_mint_rejected_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "5xx Requests (/tokens/mint)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=\"/api/v1/namespaces/{ns}/tokens/mint\",code=\"500\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Events Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (signature) (ff_blockchain_events_total{pod=\"$pod\",namespace=\"$namespace\",signature!=\"BatchPin(address,uint256,string,bytes32,bytes32,string,bytes32[])\"})",
     "legendFormat": "{{signature}}"
    }
   ]
  },
  {
   "title": "Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (signature) (rate(ff_blockchain_events_total{pod=\"$pod\",namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "2xx Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=~\"/api/v1/namespaces/{ns}/contracts/invoke\",code=~\"200|202\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=~\"/api/v1/namespaces/{ns}/contracts/invoke\",code=~\"500\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Txn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by (location,methodName) (rate(ff_blockchain_transactions_total{pod=\"$pod\",namespace=\"$namespace\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "5xx Requests (/contracts/invoke)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "ff_apiserver_rest_requests_total{route=\"/api/v1/namespaces/{ns}/contracts/invoke\",code=\"500\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Batchpin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Authored",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_batchpin_total{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ff_blockchain_events_total{signature=\"BatchPin(address,uint256,string,bytes32,bytes32,string,bytes32[])\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Average Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "(ff_broadcast_submitted_total{}+ff_private_msg_submitted_total{})/ff_batchpin_total{}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Batch Pin Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "ff_batchpin_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "authored"
    },
    {
     "expr": "ff_blockchain_events_total{signature=\"BatchPin(address,uint256,string,bytes32,bytes32,string,bytes32[])\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "completed"
    }
   ]
  }
 ]
}