---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: {{ .Release.Namespace }}
spec:
  issuerRef:
    name: selfsigned
    kind: Issuer
  isCA: true
  secretName: selfsigned-ca-tls
  commonName: selfsigned-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-ca
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: selfsigned-ca-tls
