{{/*
  Copyright © 2022 Kaleido, Inc.

  SPDX-License-Identifier: Apache-2.0

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://swww.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/}}

{{- if and .Values.erc20erc721.enabled .Values.erc20erc721.job.deployContracts.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "firefly.erc20erc721DeployContractsJobName" . }}"
  labels:
    {{- include "firefly.erc20erc721Labels" . | nindent 4 }}
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 12000
  template:
    spec:
      volumes:
        - name: deploy-scripts
          configMap:
            name: {{ include "firefly.fullname" . }}-erc20-erc721-deploy-scripts
        - name: tmp
          emptyDir: {}
      {{- with .Values.erc20erc721.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: deploy-contracts
          image: "{{ .Values.erc20erc721.image.repository }}:{{ .Values.erc20erc721.image.tag }}"
          command:
            - sh
            - -ce
            - |
              #!/bin/sh

              until STATUS=$(curl --fail -s ${ETHCONNECT_URL}${ABIS_URI}); do
                echo "Waiting for Ethconnect..."
                sleep 5
              done

              set -e

              mkdir /tmp/ff-deploy-erc20-erc721-contracts
              cp /var/lib/ff-deploy-erc20-erc721-contracts/* /tmp/ff-deploy-erc20-erc721-contracts/
              cd /tmp/ff-deploy-erc20-erc721-contracts/

              npm i
              exec node index.js
          env:
            {{- include "firefly.ethconnectUrlEnvVar" . | nindent 12 }}
            - name: ETHCONNECT_PREFIX
              value: {{ .Values.config.ethconnectPrefixLong | default "firefly" }}
            - name: ABIS_URI
              value: {{ .Values.erc20erc721.abisUri | default "/abis" }}
            - name: CONTRACTS_URI
              value: {{ .Values.erc20erc721.contractsUri | default "/contracts" }}
            - name: TOKENS_OWNER_KEY
              value: {{ .Values.erc20erc721.ownerKey | default .Values.config.organizationKey }}
            - name: ERC20_ENABLED
              value: {{ .Values.erc20erc721.erc20.enabled | quote }}
            - name: ERC20_TOKEN_NAME
              value: {{ .Values.erc20erc721.erc20.tokenName }}
            - name: ERC721_ENABLED
              value: {{ .Values.erc20erc721.erc721.enabled | quote }}
            - name: ERC721_TOKEN_NAME
              value: {{ .Values.erc20erc721.erc721.tokenName }}
          volumeMounts:
            - name: deploy-scripts
              mountPath: /var/lib/ff-deploy-erc20-erc721-contracts/
            - name: tmp
              mountPath: /tmp
      restartPolicy: Never
{{- end }}