config:
  debugEnabled: true
  adminEnabled: true
  metricsEnabled: true
  preInit: true

  organizationName: "firefly-os"
  organizationKey: "0xeb7284ce905e0665b7d42cabe31c76c45da1d331"
  fireflyContractAddress: "0xeb7284ce905e0665b7d42cabe31c76c45da1d254"

  ethconnectUrl: "http://ethconnect.firefly-os"

  postgresUrl: "postgres://postgres:firef1y@postgresql.default.svc:5432?sslmode=disable"
  postgresAutomigrate: true

  ipfsApiUrl: "http://ipfs.firefly-os:5001"
  ipfsGatewayUrl: "http://ipfs.firefly-os:8080"

  addresssResolverUrlTemplate: "http://address-resolver.firefly-os/wallets/{{.Key}}"

  httpTls:
    caFile: /etc/pki/internal/ca.crt
    certFile: /etc/pki/internal/tls.crt
    keyFile: /etc/pki/internal/tls.key
    enabled: true
    clientAuth: true

core:
  metrics:
    serviceMonitor:
      enabled: true

  extraVolumeMounts: |
    - name: firefly-mtls
      mountPath: /etc/pki/internal/

  extraVolumes: |
    - name: firefly-mtls
      secret:
        secretName: firefly-mtls-tls

dataexchange:
  certificate:
    enabled: true
    issuerRef:
      kind: ClusterIssuer
      name: selfsigned-ca

  tlsSecret:
    enabled: false