{{/*
  Copyright © 2022 Kaleido, Inc.

  SPDX-License-Identifier: Apache-2.0

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://swww.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/}}

{{- if not .Values.daemonModeEnabled }}
{{- $root := . }}
{{- range .Values.instances }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ffperf.fullname" $root }}-{{ .name }}
  labels:
    {{- include "ffperf.labels" . | nindent 4 }}
    hyperledger.io/ffperf-instance: {{ .name }}
spec:
  # we add 60s to the provided instance length to ensure the Job will be around longer enough for the test to complete
  activeDeadlineSeconds: {{ include "ffperf.instanceLengthSeconds" .length | add 60 }}
  backoffLimit: 0
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      {{- include "ffperf.selectorLabels" $root | nindent 6 }}
      hyperledger.io/ffperf-instance: {{ .name }}
  template:
    metadata:
      {{- with $root.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ffperf.selectorLabels" $root | nindent 8 }}
        hyperledger.io/ffperf-instance: {{ .name }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ffperf.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $root.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $root.Chart.Name }}
          securityContext:
            {{- toYaml $root.Values.securityContext | nindent 12 }}
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag | default (printf "v%s" $root.Chart.AppVersion) }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              #!/bin/sh
              export INSTANCE_IDX=${HOSTNAME##*-}

              ffperf run --config /etc/firefly-perf-cli/instances.yaml --instance-name {{ .name }} --daemon
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          volumeMounts:
            - mountPath: /etc/ffperf-cli
              name: config
          resources:
            {{- toYaml $root.Values.resources | nindent 12 }}
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "ffperf.fullname" $root }}-config
{{- end }}
{{- end }}