{{- if .Values.daemonModeEnabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ffperf.fullname" . }}
  labels:
    {{- include "ffperf.labels" . | nindent 4 }}
spec:
  replicas: {{ len .Values.instances }}
  selector:
    matchLabels:
      {{- include "ffperf.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "ffperf.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ffperf.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ffperf.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              #!/bin/sh
              export INSTANCE_IDX=${HOSTNAME##*-}

              ffperf run --config /etc/firefly-perf-cli/instances.yaml --instance-idx ${INSTANCE_IDX} --daemon
          ports:
            - name: http
              containerPort: 5050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          volumeMounts:
            - mountPath: /etc/ffperf-cli
              name: config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "ffperf.fullname" . }}-config
{{- end }}